# Generated by Django 3.2.4 on 2021-12-20 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_article_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
